### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by nohal**

### CODE REVIEW

**Comment by nohal** [comment]
Now also includes fixes from the O4.1 rebuild

**Comment by jongough** [comment]
Pavel,
   Is it possible for you to look at the conflicts and resolve them? I can then pull this into the master repository.

Thakns
Jon

**Comment by nohal** [comment]
Yes, I will redo it, this PR is now completely obsolete...

**Comment by seandepagnier** [comment]
obsolete

**Pull request closed without merging**
