### PR TITLE
Od json

### PR DESCRIPTION
**Pull request by jongough**
Hi,
   This is a first attempt at getting the watchdog plugin to talk to the draw plugin to obtain boundary information. I am not really sure how this plugin works yet, but this pull updates the WatchdogPrefsDialog to add an anchor watch based on a boundary and to add a boundary crossing, a copy of the landfall alarm. The WatchdogDialog has also been updated to show these.

The only bit that really works, from the draw perspective, is the getting of the boundary guid when the button is pressed in the anchor watch preferences and the boat is within a boundary. This shows the JSON messaging working, and I think it could be used in a similar way for the boundary crossing. I just don't understand the plugin well enough to know how to make it function. 

The Alarm.cpp has been updated for the boundary crossing, but I don't know how to activate it. In a similar vein I think the code for the anchor watch should be simple, but again, I am not sure what I am doing.

To test this out you will need  patch 0440 of the draw plugin as this has the JSON handler and the API's coded up.

Jon

### CODE REVIEW

**Comment by seandepagnier** [comment]
First of all, thank you for the pull request.  I was wondering when I could
use the drawing work you have for both arriving and departing from polygon
areas, distance from points, and crossing boundaries.

I'm actually in the middle of rewriting the watchdog ui to make it much
more powerful (not fixed alarms but you can have several for each type if
you like)

I will take a close look at this pull request and manually apply it as
needed, for now you probably should just wait for me to deal with it, I am
focused on the watchdog (since this morning) until everything is working
again.

Sean

**Comment by jongough** [comment]
Sean,
   I am trying to workout the best information content for the JSON messages to make them usable. I used your plugin to let me check out what was probably needed. I think Dave may need to be included in a discussion on the use of JSON messages between plugins and the main line. Currently I have:
* Source - The source app/plugin that the message came from. This should be usable as the message ID for a response message
* Msg - the message type, i.e. the 'API' you want to use
* Type - 'Request' or 'Response', used to indicate what this message is being used for
* MsgId - a text string, could be unique (may need to be in some cases) to identify this particular message

The rest of the message is up to the individual application as it would be specific to them. I think the above may be enough to ensure messages get sent and received by the correct application and can be safely ignored by the others. Perhaps there need to be two classes of message, directed and broadcast. Directed would seem sensible to cut down the load on the system for most messages.

What do you think?

Jon

**Comment by jongough** [comment]
I have put a windows installable version of my changes up in my 'Release 0450' on git so that others can see that it works, well the JSON bit at least.

**Comment by seandepagnier** [comment]
Jon,

On 7/23/15, jongough <notifications@github.com> wrote:
> Sean,
>    I am trying to workout the best information content for the JSON messages
> to make them usable. I used your plugin to let me check out what was
> probably needed. I think Dave may need to be included in a discussion on the

Probably pavel is actually more interested as he tends to deal with
this sort of thing, but Dave should be included as well.

> use of JSON messages between plugins and the main line. Currently I have:
> * Source - The source app/plugin that the message came from. This should be
> usable as the message ID for a response message
> * Msg - the message type, i.e. the 'API' you want to use
> * Type - 'Request' or 'Response', used to indicate what this message is
> being used for
> * MsgId - a text string, could be unique (may need to be in some cases) to


I think the needed fields will become obvious in time, and with json
we can always add them.

> identify this particular message
>
> The rest of the message is up to the individual application as it would be
> specific to them. I think the above may be enough to ensure messages get
> sent and received by the correct application and can be safely ignored by
> the others. Perhaps there need to be two classes of message, directed and
> broadcast. Directed would seem sensible to cut down the load on the system
> for most messages.
>
> What do you think?

The only thing I can say is in the near future I would like to extend
opencpn to send more messages for routing/tracking operations etc..
and make _all_ messages be able to get transmitted via a tcp socket.

The reason for this is so that two instances of opencpn can be
connected either locally or over a network, and routes, tracks etc..
can all remain in sync.  This mostly solves the user interface
problems with two instances of opencpn vs one instance which supports
multiple chart canvas.

So I would keep in mind, that you may have a draw plugin send a
message across the network to a watchdog plugin, and also a draw
plugin talking to another draw plugin to keep the draw regions in sync
in the other instance.

Of course this requires some work to plugins like grib and wmm to
ensure that we can either favor or insist on the local plugin for
these messages.

Sean

**Comment by jongough** [comment]
Sean,
   Is there a way to discuss this out of the mainstream OCPN forum. I don't want to exclude people, but are most people interested in this stuff?

Jon

**Pull request closed without merging**
